spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 15000
    maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none